// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import queuesgo "github.com/merlinapp/queues-go"

// Subscriber is an autogenerated mock type for the Subscriber type
type Subscriber struct {
	mock.Mock
}

// RegisterFunction provides a mock function with given fields: eventName, handler
func (_m *Subscriber) RegisterFunction(eventName string, handler queuesgo.HandlerFunc) error {
	ret := _m.Called(eventName, handler)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, queuesgo.HandlerFunc) error); ok {
		r0 = rf(eventName, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: ctx
func (_m *Subscriber) Subscribe(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
